[project]
name = "evm-contract-calls"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ecdsa>=0.19.1",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "web3>=7.14.0",
]
